### PR TITLE
plz

### PR DESCRIPTION
**Pull request by FlamingQaz**

### CODE REVIEW

**Comment by Cannicide** [comment]
Your copy of the rest of the files is outdated, insert your code into the latest version of the bot

**Comment by FlamingQaz** [comment]
Big sad

**Comment by Cannicide** [comment]
Much big sad

**Comment by Cannicide** [comment]
Your code doesn't even work btw...

There's an if statement checking for message.content inside another if statement checking for a different message.content (meaning one or both will not be triggered)

And there's a conflict with your ?coins command and the ?coins command that I already have in the code...

Not to mention how visually unpleasing the chess board is... although this part is not easily changeable, so I don't care. You can't check for the coinflip heads/tails response AND check for the coinflip command at the same time. Fix that, and the code will be good to go.

**Comment by Cannicide** [comment]
Copying senpai command and committing without the conflicts

**Pull request closed without merging**
